### PR TITLE
Fix `modulus status` command.

### LINKED ISSUE #144: update status url
Since we moved to https://status.progress.com, we need to [update the url](https://github.com/onmodulus/modulus-cli/blob/master/lib/commands/status.js#L28)

Reference: https://github.com/onmodulus/modulus-cli/issues/142#issuecomment-241089835

```
TypeError: Cannot call method 'forEach' of undefined
    at Request._callback (/usr/local/lib/node_modules/modulus/lib/commands/status.js:41:21)
    at Request.self.callback (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

### PR DESCRIPTION
**Pull request by theworkflow**
Only print components part of the Modulus stack

Closes #144

### CODE REVIEW

File: lib/commands/status.js [hunk 1]
```diff
@@ -25,20 +25,28 @@ var request       = require('request');
...
 Status.get = function (callback) {
   request.get({
     url: url,
     json: true
   },
   function (err, response, body) {
+    var table = [];
+
     if (err) return callback(err);
+    if (!body.components) return callback('Status not available');
```
Comment (franvarney) [inline lib/commands/status.js]: might want to also check `!body.components.length` ?
